### ISSUE TITLE
Sort project card metadata when writing to YAML

### ISSUE THREAD

**Issue by jhelsel11** [wsp-sag/Lasso#62]
@i-am-sijia, the project cards you create for the client_met_council_network repo don't have metadata at the top (e.g. project, category, tags, dependencies). Same goes for the project card I made. Is there something I should do to have it create the skeleton of the metadata for me to fill in? Or is its absence a bug in lasso?

**Comment by i-am-sijia** [comment]
They have metadata for [projects](https://github.com/wsp-sag/client_met_council_network/blob/b8d4779221b1c61fa25527c31828a552f3526040/project_cards/i394_reversible_lane.yml#L290) and [categories](https://github.com/wsp-sag/client_met_council_network/blob/b8d4779221b1c61fa25527c31828a552f3526040/project_cards/i394_reversible_lane.yml#L111), in either the ones I gave you or the one you made.  Can you see them?    The reason "project" is not at the top of files is because network wrangler is default sorting them.

Tags and dependencies are not written out, as they aren't necessary for all project cards.   We can add them if needed.   I think this can happen when the user has the project card written out,  manually add those info (project, tag, dependency) to whatever they like.   Or, we can include them as required arguments when running Lasso project card creation.  Either way sounds good to me, and both require the user to know what to type.  We should discuss this.

cc: @e-lo @DavidOry what do you think?

**Comment by jhelsel11** [comment]
Is it possible to add them but leave them blank? That way the user can edit them directly?

**Comment by i-am-sijia** [comment]
Yes, that's how "project" is treated right now, user can edit them directly if needed.  We can do the same for "tag" and "dependency".

**Comment by DavidOry** [comment]
This is a priority for Rachel. Can we please:

(1) Make sure project is at the top, followed by tags and dependency;
(2) Add tag and dependency with blanks in the skeleton.

**Comment by e-lo** [comment]
@i-am-sijia I can work on this

**Comment by e-lo** [comment]
Fixed in https://github.com/wsp-sag/network_wrangler/commit/f4d591a4672bab9fc603826ec62040bf8711fd5c
