### ISSUE TITLE
Project cards not changing assignment groups

### ISSUE THREAD

**Issue by jhelsel11** [wsp-sag/Lasso#88]
I applied a series of project cards to correct large problems with the assignment groups in the original network Sijia developed (prior to November 2019). These project cards did not change the assignment group in the highway network as expected. 

@i-am-sijia suggested that either Network Wrangler or Lasso is preventing changes to the assignment group without some override key. @kulshresthaa, do you know whether it's the case that project cards with changes to the assignment group will fail to propagate those changes back to the fixed width network that is written to disk by lasso?

**Comment by jhelsel11** [comment]
@DavidOry, tagging you so you're up to date for Met Council meetings.

**Comment by i-am-sijia** [comment]
`assign_group` is a calculated variable in Met Council standard, instead of being a network standard variable for wrangler.   And Lasso calculates it in the step: network standard to Met Council standard.

We need to make sure:

1. Network after wrangler applying the project cards has `assign_group`
2. Update Lasso to take `assign_group` from wrangler instead of calculating and overwriting

**Comment by i-am-sijia** [comment]
Wrangler cannot take `existing` for `assign_group`

```
  properties:
  - existing: 1
    property: assign_group
    set: 2
```
because `assign_group` is not an attribute in network standard.  The solution is to remove `existing`

```
  properties:
  - property: assign_group
    set: 2
```
so that wrangler can pass along the `assign_group` value to Lasso.

I will make changes in Lasso to avoid overwriting any `assign_group` values from wrangler.

**Comment by e-lo** [comment]
I think it would be fairly easy to make Wrangler a little more resilient here. 

Specifically, I believe the desired function should be:
- have a setting in Wrangler (which we should make more configurable) that is `existing_value_strict`
- if have an `existing:` but the value doesn't match:
        - if `existing_strict`, then fail
        - otherwise, warn
- if have an `existing:` but variable doesn't exist, give a warning (should it fail if we are strict?)

**Comment by jhelsel11** [comment]
@i-am-sijia, I reran scenario creation and exported the fixed width files with the updates you made yesterday. The link assignment groups were not changed to the appropriate values. Let me know if you want to touch base or run a smaller test network to confirm.
